version: '3.6'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=development_pass
      - POSTGRES_DB=nodejs-eb-api
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - 5436:5432
volumes:
  nodejs_api_data: {}
